In [3]:
from bs4 import BeautifulSoup
import requests
from pprint import pprint
import pandas as pd

In [4]:
# load the data
data = pd.read_csv("sp500.csv")

In [103]:
data

    Symbol                                 Name                      Sector
0      MMM                           3M Company                 Industrials
1      AOS                      A.O. Smith Corp                 Industrials
2      ABT                  Abbott Laboratories                 Health Care
3     ABBV                          AbbVie Inc.                 Health Care
4      ACN                        Accenture plc      Information Technology
5     ATVI                  Activision Blizzard      Information Technology
6      AYI                    Acuity Brands Inc                 Industrials
7     ADBE                    Adobe Systems Inc      Information Technology
8      AAP                   Advance Auto Parts      Consumer Discretionary
9      AMD           Advanced Micro Devices Inc      Information Technology
10     AES                             AES Corp                   Utilities
11     AFL                            AFLAC Inc                  Financials
12       A             Agilent Technologies Inc                 Health Care
13     APD         Air Products & Chemicals Inc                   Materials
14    AKAM              Akamai Technologies Inc      Information Technology
15     ALK                 Alaska Air Group Inc                 Industrials
16     ALB                       Albemarle Corp                   Materials
17     ARE  Alexandria Real Estate Equities Inc                 Real Estate
18    ALXN              Alexion Pharmaceuticals                 Health Care
19    ALGN                     Align Technology                 Health Care
20     LNT                  Alliant Energy Corp                   Utilities
21     ALL                        Allstate Corp                  Financials
22   GOOGL                 Alphabet Inc Class A      Information Technology
23    GOOG                 Alphabet Inc Class C      Information Technology
24      MO                     Altria Group Inc            Consumer Staples
25    AMZN                       Amazon.com Inc      Consumer Discretionary
26     AEE                          Ameren Corp                   Utilities
27     AAL              American Airlines Group                 Industrials
28     AEP              American Electric Power                   Utilities
29     AXP                  American Express Co                  Financials
..     ...                                  ...                         ...
407   VRSN                        Verisign Inc.      Information Technology
408     VZ               Verizon Communications  Telecommunication Services
409   VRTX           Vertex Pharmaceuticals Inc                 Health Care
410   VIAB                          Viacom Inc.      Consumer Discretionary
411      V                            Visa Inc.      Information Technology
412    VNO                 Vornado Realty Trust                 Real Estate
413    VMC                     Vulcan Materials                   Materials
414    WMT                      Wal-Mart Stores            Consumer Staples
415    WBA             Walgreens Boots Alliance            Consumer Staples
416     WM                Waste Management Inc.                 Industrials
417    WAT                   Waters Corporation                 Health Care
418    WEC                 Wec Energy Group Inc                   Utilities
419    WFC                          Wells Fargo                  Financials
420    HCN                       Welltower Inc.                 Real Estate
421    WDC                      Western Digital      Information Technology
422     WU                     Western Union Co      Information Technology
423    WRK                     WestRock Company                   Materials
424     WY                   Weyerhaeuser Corp.                 Real Estate
425    WHR                      Whirlpool Corp.      Consumer Discretionary
426    WMB                        Williams Cos.                      Energy
427    WYN                    Wyndham Worldwide      Consumer Discretionary
428   WYNN                     Wynn Resorts Ltd      Consumer Discretionary
429    XEL                      Xcel Energy Inc                   Utilities
430    XRX                          Xerox Corp.      Information Technology
431   XLNX                           Xilinx Inc      Information Technology
432     XL                           XL Capital                  Financials
433    YUM                      Yum! Brands Inc      Consumer Discretionary
434    ZBH               Zimmer Biomet Holdings                 Health Care
435   ZION                        Zions Bancorp                  Financials
436    ZTS                               Zoetis                 Health Care

[437 rows x 3 columns]

In [ ]:
# for data to be jsonifyed
stock_dictionary = {}
for stock_name in list(data.Symbol):
    
    url = "https://finance.yahoo.com/quote/"+stock_name
    request = requests.get(url)
    soup4 = BeautifulSoup(request.text, 'html.parser')
    result = soup4.find_all("table")
    if result != []:
        
        try:
            previous_close_number = float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[0])\
                                              .split("<")[1].split(">")[1])
        except ValueError:

            previous_close_number = "N/A"
            
        except IndexError:
            previous_close_number = "N/A"




        try:
            open_number = float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[1])\
                                .split("<")[1].split(">")[1])
        except ValueError:
            open_number = "N/A"
        except IndexError:
            open_number = "N/A"



        try:
            bid_number = str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[2])\
                .split("<")[1].split(">")[1]
        except IndexError:
            bid_number = "N/A"
  

        try:
            ask_number = str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[3])\
                .split("<")[1].split(">")[1]
        except IndexError:
            ask_number = "N/A"


        try:
            day_range_str = str(result[0].find_all(attrs={'class','Ta(end)'})[4])\
                .split("<")[1].split(">")[1]
        except IndexError: 
            day_range_str = "N/A"



        fifty_two_week_range_str = str(result[0].find_all(attrs=\
            {'class','Ta(end)'})[5]).split("<")[1].split(">")[1]


        # the purpose of the if statements is to take the comma out of the volume (of the stock) number
        # because the comma prevents the number from becoming a float
        # it is first checking if there is one comma in the string then 
        # checking if there is two string in the volume
        # if there is one comma in the string the first if statement will return as true
        # if there are two commas in the string then the second if statement will return as true

        try:
            volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[1])
        except IndexError:
            volume_number = "N/A"

          #volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[1]+
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[2])




        #the same thing we did for the volume we are going to do for the average volume
        # because the comma in the string will prevent it from becoming a float


    #         average_volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[0]+\
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[1])

        try:
            average_volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+\
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[1]+\
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[2])
        except IndexError:
            average_volume_number = "N/A"




        try:
            market_cap_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[0])\
                                    .split("<")[1].split(">")[1].split("B")[0])
        except ValueError:
            market_cap_number = "N/A"
        except IndexError:
            market_cap_number = "N/A"



        try:
            beta_3y_monthly_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[1])\
                                           .split("<")[1].split(">")[1])
        except ValueError:
            beta_3y_monthly_number = "N/A"
        except IndexError:
            beta_3y_monthly_number = "N/A"


        try:
            pe_ratio_number = float(str(result[1]\
                 .find_all(attrs={'class','Trsdu(0.3s)'})[2])\
                  .split("<")[1].split(">")[1])
        except ValueError:
            pe_ratio_number = "N/A"
        except IndexError:
            pe_ratio_number = "N/A"



        try:
            eps_ttm_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[3])
                .split("<")[1].split(">")[1])
        except ValueError:
            eps_ttm_number = "N/A"
        except IndexError:
            eps_ttm_number = "N/A"            


        try:
            earning_date = str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[4])\
                .split("<")[1].split(">")[1]
        except IndexError:
            earning_date = "N/A"




        try:
            forward_dividend_number = float(str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[5])\
                .split("<")[1].split(">")[1]\
                .split(" ")[0])
        except ValueError:
            forward_dividend_number = "N/A"
        except IndexError:
            forward_dividend_number = "N/A"





#         try:
#             forward_yeild_number = float(str(result[1].find_all\
#                 (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[5])\
#                 .split("<")[1].split(">")[1]\
#                 .split(" ")[1].split("%")[0]\
#                 .split("(")[1])
#         except ValueError:
#             forward_yeild_number = "N/A"




        ex_dividend_date = str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[4])\
            .split("<")[1].split(">")[1]




        try:
            one_year_target_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[5])\
                .split("<")[1].split(">")[1])
        except ValueError:
            one_year_target_number = "N/A"

        stock_dictionary.update({stock_name:{
        "stock_name":stock_name,
        "previous_close":previous_close_number,
        "open":open_number,
        "bid":bid_number,
        "ask":ask_number,
        "day_range":day_range_str,
        "52week_range": fifty_two_week_range_str,
        "volume": volume_number,
        "avg_volume":average_volume_number,
        "market cap": market_cap_number,
        "beta": beta_3y_monthly_number,
        "pe_ratio": pe_ratio_number,
        "eps":eps_ttm_number,
        "earnings_date":earning_date,
        "forward_div":forward_dividend_number,
        "forward_yeild": forward_yeild_number,
        "ex_div_date":ex_dividend_date,
        "1year_target_est":one_year_target_number

        }})

In [92]:
data = pd.read_csv("sp500.csv") 

list_list = []
for i in list(range(310,len(data.Symbol))):
    list_list.append(data.Symbol[i])
    
data.Symbol[346]

'CRM'

In [93]:
# for data to be put into a pandas dataframe

stock_name_list=[]
previous_close_list=[]
open_list = []
bid_list=[]
ask_list = []
day_range_list =[]
week_52_range_list=[]
volume_list=[]
avg_volume_list=[]
market_cap_list=[]
beta_list=[]
pe_ratio_list=[]
eps_list=[]
earnings_date_list=[]
forward_div_list=[]
forward_yeild_list=[]
ex_div_date_list=[]
one_year_target_est_list=[]
delete_list_today = []
for stock_name in list(data.Symbol):
    
    url = "https://finance.yahoo.com/quote/"+stock_name
    request = requests.get(url)
    soup4 = BeautifulSoup(request.text, 'html.parser')
    result = soup4.find_all("table")
    if result != []:
        
        try:
            previous_close_number = float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[0])\
                                              .split("<")[1].split(">")[1])
        except ValueError:

            previous_close_number = "N/A"
            
        except IndexError:
            previous_close_number = "N/A"




        try:
            open_number = float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[1])\
                                .split("<")[1].split(">")[1])
        except ValueError:
            open_number = "N/A"
        except IndexError:
            open_number = "N/A"



        try:
            bid_number = str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[2])\
                .split("<")[1].split(">")[1]
        except IndexError:
            bid_number = "N/A"
  

        try:
            ask_number = str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[3])\
                .split("<")[1].split(">")[1]
        except IndexError:
            ask_number = "N/A"


        try:
            day_range_str = str(result[0].find_all(attrs={'class','Ta(end)'})[4])\
                .split("<")[1].split(">")[1]
        except IndexError: 
            day_range_str = "N/A"



        fifty_two_week_range_str = str(result[0].find_all(attrs=\
            {'class','Ta(end)'})[5]).split("<")[1].split(">")[1]


        # the purpose of the if statements is to take the comma out of the volume (of the stock) number
        # because the comma prevents the number from becoming a float
        # it is first checking if there is one comma in the string then 
        # checking if there is two string in the volume
        # if there is one comma in the string the first if statement will return as true
        # if there are two commas in the string then the second if statement will return as true

        try:
            volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[1])
        except IndexError:
            volume_number = "N/A"

          #volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[1]+
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[2])




        #the same thing we did for the volume we are going to do for the average volume
        # because the comma in the string will prevent it from becoming a float


    #         average_volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[0]+\
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[1])

        try:
            average_volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+\
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[1]+\
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[2])
        except IndexError:
            average_volume_number = "N/A"




        try:
            market_cap_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[0])\
                                    .split("<")[1].split(">")[1].split("B")[0])
        except ValueError:
            market_cap_number = "N/A"
        except IndexError:
            market_cap_number = "N/A"



        try:
            beta_3y_monthly_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[1])\
                                           .split("<")[1].split(">")[1])
        except ValueError:
            beta_3y_monthly_number = "N/A"
        except IndexError:
            beta_3y_monthly_number = "N/A"


        try:
            pe_ratio_number = float(str(result[1]\
                 .find_all(attrs={'class','Trsdu(0.3s)'})[2])\
                  .split("<")[1].split(">")[1])
        except ValueError:
            pe_ratio_number = "N/A"
        except IndexError:
            pe_ratio_number = "N/A"



        try:
            eps_ttm_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[3])
                .split("<")[1].split(">")[1])
        except ValueError:
            eps_ttm_number = "N/A"
        except IndexError:
            eps_ttm_number = "N/A"            


        try:
            earning_date = str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[4])\
                .split("<")[1].split(">")[1]
        except IndexError:
            earning_date = "N/A"




        try:
            forward_dividend_number = float(str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[5])\
                .split("<")[1].split(">")[1]\
                .split(" ")[0])
        except ValueError:
            forward_dividend_number = "N/A"
        except IndexError:
            forward_dividend_number = "N/A"





        try:
            forward_yeild_number = float(str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[5])\
                .split("<")[1].split(">")[1]\
                .split(" ")[1].split("%")[0]\
                .split("(")[1])
        except ValueError:
            forward_yeild_number = "N/A"
        except IndexError:
            forward_yeild_number = "N/A"




        ex_dividend_date = str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[4])\
            .split("<")[1].split(">")[1]




        try:
            one_year_target_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[5])\
                .split("<")[1].split(">")[1])
        except ValueError:
            one_year_target_number = "N/A"

        

        stock_name_list.append(stock_name)
        previous_close_list.append(previous_close_number)
        open_list.append(open_number)
        bid_list.append(bid_number)
        ask_list.append(ask_number)
        day_range_list.append(day_range_str)
        week_52_range_list.append(fifty_two_week_range_str)
        volume_list.append(volume_number)
        avg_volume_list.append(average_volume_number)
        market_cap_list.append(market_cap_number)
        beta_list.append(beta_3y_monthly_number)
        pe_ratio_list.append(pe_ratio_number)
        eps_list.append(eps_ttm_number)
        earnings_date_list.append(earning_date)
        forward_div_list.append(forward_dividend_number)
        forward_yeild_list.append(forward_yeild_number)
        ex_div_date_list.append(ex_dividend_date)
        one_year_target_est_list.append(one_year_target_number)

    else:
        delete_list_today.append(stock_name)

In [99]:
len(one_year_target_est_list)+len(delete_list_today)

437

In [100]:
len(data)

437

In [106]:
finished_df_today = pd.DataFrame({
    "Stock_Ticker":stock_name_list,
    "Previous_Close": previous_close_list,
    "Open":open_list,
    "Bid": bid_list,
    "Ask":ask_list,
    "Days_Range":day_range_list,
    "52_Week_Range":week_52_range_list,
    "Volume":volume_list,
    "Avg_Volume":avg_volume_list,
    "Market_Cap":market_cap_list,
    "Beta_3Y_Monthly)":beta_list,
    "PE Ratio_TTM":pe_ratio_list,
    "EPS_TTM":eps_list,
    "Earnings_Date":earnings_date_list,
    "Forward_Dividend":forward_div_list,
    "Forward_Yeild":forward_yeild_list,
    "Ex_Dividend_Date":ex_div_date_list,
    "one_y_Target_Est":one_year_target_est_list
})

In [ ]:
pwd

In [108]:
finished_df_today.to_csv('final_df_2019.csv',index=False)

In [ ]:
url = "https://web.archive.org/web/20170104214153/https://finance.yahoo.com/quote/aapl"
request = requests.get(url)
soup4 = BeautifulSoup(request.text, 'html.parser')
result = soup4.find_all("data-test")

In [ ]:
result

In [ ]:
soup4.find_all(attrs={'class',"Ta(end)"})[1]

In [ ]:
    url = "https://finance.yahoo.com/quote/aapl"
    request = requests.get(url)
    soup4 = BeautifulSoup(request.text, 'html.parser')
    result = soup4.find_all("tbody")

In [ ]:
result[1].find_all("tr")[0]

In [ ]:
.find_all(attrs={'data-test','MARKET_CAP-value'})

In [77]:
data = pd.read_csv("sp500.csv") 

list_list = []
for i in list(range(310,len(data.Symbol))):
    list_list.append(data.Symbol[i])
    
data.Symbol[357]

'SPG'

In [104]:
# for data to be jsonifyed
data = pd.read_csv("sp500.csv") 
stock_dictionary_2018 = {}
symbols_to_delete_list = []
for stock_name in stock_name_list:
    
    url = "https://web.archive.org/web/20180614060458/https://finance.yahoo.com/quote/"+stock_name
    request = requests.get(url)
    soup4 = BeautifulSoup(request.text, 'html.parser')
    result = soup4.find_all("table")
    if result != []:
        
        try:
            previous_close_number = float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[0])\
                                              .split("<")[1].split(">")[1])
        except ValueError:

            previous_close_number = "N/A"
            
        except IndexError:
            previous_close_number = "N/A"




        try:
            open_number = float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[1])\
                                .split("<")[1].split(">")[1])
        except ValueError:
            open_number = "N/A"
        except IndexError:
            open_number = "N/A"



        try:
            bid_number = str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[2])\
                .split("<")[1].split(">")[1]
        except IndexError:
            bid_number = "N/A"
  

        try:
            ask_number = str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[3])\
                .split("<")[1].split(">")[1]
        except IndexError:
            ask_number = "N/A"


        try:
            day_range_str = str(result[0].find_all(attrs={'class','Ta(end)'})[4])\
                .split("<")[1].split(">")[1]
        except IndexError: 
            day_range_str = "N/A"



        fifty_two_week_range_str = str(result[0].find_all(attrs=\
            {'class','Ta(end)'})[5]).split("<")[1].split(">")[1]


        # the purpose of the if statements is to take the comma out of the volume (of the stock) number
        # because the comma prevents the number from becoming a float
        # it is first checking if there is one comma in the string then 
        # checking if there is two string in the volume
        # if there is one comma in the string the first if statement will return as true
        # if there are two commas in the string then the second if statement will return as true

        try:
            volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[1])
        except IndexError:
            volume_number = "N/A"

          #volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[1]+
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[2])




        #the same thing we did for the volume we are going to do for the average volume
        # because the comma in the string will prevent it from becoming a float


    #         average_volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[0]+\
    #         str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[1])

        try:
            average_volume_number =float(str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[4]).split("<")[1].split(">")[1].split(",")[0]+\
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[1]+\
                str(result[0].find_all(attrs={'class','Trsdu(0.3s)'})[5]).split("<")[1].split(">")[1].split(",")[2])
        except IndexError:
            average_volume_number = "N/A"




        try:
            market_cap_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[0])\
                                    .split("<")[1].split(">")[1].split("B")[0])
        except ValueError:
            market_cap_number = "N/A"
        except IndexError:
            market_cap_number = "N/A"



        try:
            beta_3y_monthly_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[1])\
                                           .split("<")[1].split(">")[1])
        except ValueError:
            beta_3y_monthly_number = "N/A"
        except IndexError:
            beta_3y_monthly_number = "N/A"


        try:
            pe_ratio_number = float(str(result[1]\
                 .find_all(attrs={'class','Trsdu(0.3s)'})[2])\
                  .split("<")[1].split(">")[1])
        except ValueError:
            pe_ratio_number = "N/A"
        except IndexError:
            pe_ratio_number = "N/A"



        try:
            eps_ttm_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[3])
                .split("<")[1].split(">")[1])
        except ValueError:
            eps_ttm_number = "N/A"
        except IndexError:
            eps_ttm_number = "N/A"            


        try:
            earning_date = str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[4])\
                .split("<")[1].split(">")[1]
        except IndexError:
            earning_date = "N/A"




        try:
            forward_dividend_number = float(str(result[1].find_all\
                (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[5])\
                .split("<")[1].split(">")[1]\
                .split(" ")[0])
        except ValueError:
            forward_dividend_number = "N/A"
        except IndexError:
            forward_dividend_number = "N/A"





#         try:
#             forward_yeild_number = float(str(result[1].find_all\
#                 (attrs={'class',"Ta(end) Fw(600) Lh(14px)"})[5])\
#                 .split("<")[1].split(">")[1]\
#                 .split(" ")[1].split("%")[0]\
#                 .split("(")[1])
#         except ValueError:
#             forward_yeild_number = "N/A"




        ex_dividend_date = str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[4])\
            .split("<")[1].split(">")[1]




        try:
            one_year_target_number = float(str(result[1].find_all(attrs={'class','Trsdu(0.3s)'})[5])\
                .split("<")[1].split(">")[1])
        except ValueError:
            one_year_target_number = "N/A"

        stock_dictionary_2018.update({stock_name:{
        "stock_name":stock_name,
        "previous_close":previous_close_number,
        "open":open_number,
        "bid":bid_number,
        "ask":ask_number,
        "day_range":day_range_str,
        "52week_range": fifty_two_week_range_str,
        "volume": volume_number,
        "avg_volume":average_volume_number,
        "market cap": market_cap_number,
        "beta": beta_3y_monthly_number,
        "pe_ratio": pe_ratio_number,
        "eps":eps_ttm_number,
        "earnings_date":earning_date,
        "forward_div":forward_dividend_number,
        #"forward_yeild": forward_yeild_number,
        "ex_div_date":ex_dividend_date,
        "1year_target_est":one_year_target_number

        }})
    elif result == []:
        symbols_to_delete_list.append(stock_name)

In [105]:
symbols_to_delete_list

[]

In [74]:
str(result[0].find_all(attrs=\
           {'class','Ta(end)'}))

'[]'

In [109]:
data = pd.read_csv("sp500.csv") 
prev_close_list_2018 = []
open_list_2018 = []
bid_list_2018 = []
ask_list_2018 = []
day_range_list_2018 = []
fifty_two_range_list_2018 = []
volume_list_2018 = []
avg_volume_list_2018 = []
market_cap_list_2018 = []
beta_list_2018 = []
pe_ratio_list_2018 =[]
earnings_date_list_2018 =[]
forward_div_list_2018 =[]
forward_yield_list_2018 =[]
ex_div_date_list_2018 =[]
one_year_target_list_2018=[]
eps_list_2018 = []
for stock_name in stock_name_list:
    prev_close_list_2018.append(stock_dictionary_2018[stock_name]["previous_close"])
    open_list_2018.append(stock_dictionary_2018[stock_name]['open'])
    ask_list_2018.append(stock_dictionary_2018[stock_name]["ask"])
    bid_list_2018.append(stock_dictionary_2018[stock_name]["bid"])
    day_range_list_2018.append(stock_dictionary_2018[stock_name]["day_range"])
    fifty_two_range_list_2018.append(stock_dictionary_2018[stock_name]["52week_range"])
    volume_list_2018.append(stock_dictionary_2018[stock_name]["volume"])
    avg_volume_list_2018.append(stock_dictionary_2018[stock_name]["avg_volume"])
    market_cap_list_2018.append(stock_dictionary_2018[stock_name]["market cap"])
    beta_list_2018.append(stock_dictionary_2018[stock_name]["beta"])
    pe_ratio_list_2018.append(stock_dictionary_2018[stock_name]["pe_ratio"])
    earnings_date_list_2018.append(stock_dictionary_2018[stock_name]["earnings_date"])
    forward_div_list_2018.append(stock_dictionary_2018[stock_name]["forward_div"])
    #forward_yield_list_2018.append(stock_dictionary_2018[stock_name]["forward_yeild"])
    ex_div_date_list_2018.append(stock_dictionary_2018[stock_name]["ex_div_date"])
    one_year_target_list_2018.append(stock_dictionary_2018[stock_name]["1year_target_est"])
    eps_list_2018.append(stock_dictionary_2018[stock_name]["eps"])

In [122]:
finished_df_2018 = pd.DataFrame({
    "Stock_Ticker":stock_name_list,
    "Previous_Close": prev_close_list_2018,
    "Open":open_list_2018,
    "Bid": bid_list_2018,
    "Ask":ask_list_2018,
    "Days_Range":day_range_list_2018,
    "52_Week_Range":fifty_two_range_list_2018,
    "Volume":volume_list_2018,
    "Avg_Volume":avg_volume_list_2018,
    "Market_Cap":market_cap_list_2018,
    "Beta_3Y_Monthly":beta_list_2018,
    "PE Ratio_TTM":pe_ratio_list_2018,
    "EPS_TTM":eps_list_2018,
    "Earnings_Date":earnings_date_list_2018,
    "Forward_Dividend":forward_div_list_2018,
    "Ex_Dividend_Date":ex_div_date_list_2018,
    "one_y_Target_Est":one_year_target_list_2018
})

ValueError: arrays must all be same length

In [111]:
finished_df_2018.to_csv('final_df_2018.csv',index=False)

In [112]:
data = pd.read_csv("sp500.csv") 
symbol_list = list(data.Symbol)
stock_dictionary = {}
symbols_to_delete_list = []
for stock_name in stock_name_list:
    url = "https://web.archive.org/web/20170104214153/https://finance.yahoo.com/quote/"+stock_name
    request = requests.get(url)
    soup4 = BeautifulSoup(request.text, 'html.parser')
    
    if soup4.find_all("table") != []:
        # scraping for the previous close
        prev_close = str(soup4.find_all("table")[1].find_all("td")[1])\
        .split("<")[1].split(">")[1]
        try:
            prev_close = float(prev_close)
        except ValueError:
            prev_close = "N/A"


        # scraping the open value
        open_str = str(soup4.find_all("table")[1]\
                   .find_all("td")[3]).split("<")[1].split(">")[1]
        try:
            open_value = float(open_str)
        except ValueError:
            open_value = "N/A"

        # scraping for the bid, it will be a string    
        bid_str = str(soup4.find_all("table")[1]\
                      .find_all("td")[5]).split("<")[1].split(">")[1]


        # scraping for the ask, it will be a string
        ask_str = str(soup4.find_all("table")[1]\
                      .find_all("td")[7]).split("<")[1].split(">")[1]

        # scraping for the day's range, it will be a string
        day_range_str = str(soup4.find_all("table")[1]\
                            .find_all("td")[9]).split("<")[1].split(">")[1]

        #scraping for the 52 week range, it will be a string
        fifty_two_week_range_str = str(soup4.find_all("table")[1]\
                        .find_all("td")[11]).split("<")[1].split(">")[1]
        # scraping for the volume
        volume_str = str(soup4.find_all("table")[1].find_all("td")[13])\
        .split("<")[1].split(">")[1].replace(",","")

        try:
            volume_value = float(volume_str)
        except ValueError:
            volume_value = "N/A"

        # scraping for the average volume 
        avg_volume_str = str(soup4.find_all("table")[1].find_all("td")[15])\
        .split("<")[1].split(">")[1].replace(",","")

        try:
            avg_volume_value = float(avg_volume_str)
        except ValueError:
            avg_volume_value = "N/A"


        # scraping for the market cap value
        market_cap_value_str = str(soup4.find_all("table")[2].find_all("td")[1])\
                             .split("<")[1].split(">")[1].replace("B","")
        try:
            market_cap_value = float(market_cap_value_str)
        except ValueError:
            market_cap_value = "N/A"


        # scraping for the beta value
        beta_str = str(soup4.find_all("table")[2].find_all("td")[3])\
                             .split("<")[1].split(">")[1]
        try:
            beta_value = float(beta_str)
        except ValueError:
            beta_value = "N/A"

        # scraping for the PE ratio (TTM)
        pe_ratio_str = str(soup4.find_all("table")[2].find_all("td")[5])\
                             .split("<")[1].split(">")[1]
        try:
            pe_ratio_value = float(pe_ratio_str)
        except ValueError:
            pe_ratio_value = "N/A"

        #scraping for the EPS (TTM)
        eps_str = str(soup4.find_all("table")[2].find_all("td")[7])\
                             .split("<")[1].split(">")[1]
        try:
            eps_value = float(eps_str)
        except ValueError:
            eps_value = "N/A"


        # scraping for the earnings date
        earnings_date_str = str(soup4.find_all("table")[2].find_all("td")[9])\
                             .split("<")[1].split(">")[1]

        # scraping for the dividend
        try:
            dividend_value = float(str(soup4.find_all("table")[2].find_all("td")[11])\
                             .split("<")[1].split(">")[1].split(" ")[0])
        except ValueError:
            dividend_value = "N/A"

        # scraping for the yield
        if str(soup4.find_all("table")[2].find_all("td")[11])\
                             .split("<")[1].split(">")[1]\
        != "N/A":
            yield_str = str(soup4.find_all("table")[2].find_all("td")[11])\
                                     .split("<")[1].split(">")[1]\
                                     .split("(")[1].replace("%)","")
            try:
                yield_value = float(yield_str)
            except ValueError:
                yield_value = "N/A"

        else:
            yield_value = "N/A"

        # scraping for the ex-dividend date
        ex_div_date = str(soup4.find_all("table")[2].find_all("td")[13])\
                             .split("<")[1].split(">")[1]

        #scraping for the 1 year target estimate
        one_year_target_date_str = str(soup4.find_all("table")[2].find_all("td")[15])\
                             .split("<")[1].split(">")[1]

        try:
            one_year_target_date_value = float(one_year_target_date_str)
        except ValueError:
            one_year_target_date_value = "N/A"

        stock_dictionary.update({stock_name:{
            "stock_name":stock_name,
            "previous_close":prev_close,
            "open":open_value,
            "bid":bid_str,
            "ask":ask_str,
            "day_range":day_range_str,
            "52week_range": fifty_two_week_range_str,
            "volume": volume_value,
            "avg_volume":avg_volume_value,
            "market cap": market_cap_value,
            "beta": beta_value,
            "pe_ratio": pe_ratio_value,
            "eps":eps_value,
            "earnings_date":earnings_date_str,
            "forward_div":dividend_value,
            "forward_yeild": yield_value,
            "ex_div_date":ex_div_date,
            "1year_target_est":one_year_target_date_value

        }})
    elif soup4.find_all("table") == []:
        symbols_to_delete_list.append(stock_name)

In [113]:
stock_name

'ZTS'

In [115]:
data = pd.read_csv("sp500.csv") 
prev_close_list_2017 = []
open_list_2017 = []
bid_list_2017 = []
ask_list_2017 = []
day_range_list_2017 = []
fifty_two_range_list_2017 = []
volume_list_2017 = []
avg_volume_list_2017 = []
market_cap_list_2017 = []
beta_list_2017 = []
pe_ratio_list_2017 =[]
earnings_date_list_2017 =[]
forward_div_list_2017 =[]
forward_yield_list_2017 =[]
ex_div_date_list_2017 =[]
one_year_target_list_2017=[]
eps_list_2017 = []
for stock_name in stock_name_list:
    prev_close_list_2017.append(stock_dictionary_2018[stock_name]["previous_close"])
    open_list_2017.append(stock_dictionary_2018[stock_name]['open'])
    ask_list_2017.append(stock_dictionary_2018[stock_name]["ask"])
    bid_list_2017.append(stock_dictionary_2018[stock_name]["bid"])
    day_range_list_2017.append(stock_dictionary_2018[stock_name]["day_range"])
    fifty_two_range_list_2017.append(stock_dictionary_2018[stock_name]["52week_range"])
    volume_list_2017.append(stock_dictionary_2018[stock_name]["volume"])
    avg_volume_list_2017.append(stock_dictionary_2018[stock_name]["avg_volume"])
    market_cap_list_2017.append(stock_dictionary_2018[stock_name]["market cap"])
    beta_list_2017.append(stock_dictionary_2018[stock_name]["beta"])
    pe_ratio_list_2017.append(stock_dictionary_2018[stock_name]["pe_ratio"])
    earnings_date_list_2017.append(stock_dictionary_2018[stock_name]["earnings_date"])
    forward_div_list_2017.append(stock_dictionary_2018[stock_name]["forward_div"])
    #forward_yield_list_2018.append(stock_dictionary_2018[stock_name]["forward_yeild"])
    ex_div_date_list_2017.append(stock_dictionary_2018[stock_name]["ex_div_date"])
    one_year_target_list_2017.append(stock_dictionary_2018[stock_name]["1year_target_est"])
    eps_list_2017.append(stock_dictionary_2018[stock_name]["eps"])

In [120]:
finished_df_2017 = pd.DataFrame({
    "Stock_Ticker":stock_name_list,
    "Previous_Close": prev_close_list_2017,
    "Open":open_list_2017,
    "Bid": bid_list_2017,
    "Ask":ask_list_2017,
    "Days_Range":day_range_list_2017,
    "52_Week_Range":fifty_two_range_list_2017,
    "Volume":volume_list_2017,
    "Avg_Volume":avg_volume_list_2017,
    "Market_Cap":market_cap_list_2017,
    "Beta_3Y_Monthly":beta_list_2017,
    "PE Ratio_TTM":pe_ratio_list_2017,
    "EPS_TTM":eps_list_2017,
    "Earnings_Date":earnings_date_list_2017,
    "Forward_Dividend":forward_div_list_2017,
    "Ex_Dividend_Date":ex_div_date_list_2017,
    "one_y_Target_Est":one_year_target_list_2017
})

In [121]:
finished_df_2017.to_csv('final_df_2017.csv',index=False)

In [129]:
list(finished_df_2017.columns)

['Stock_Ticker',
 'Previous_Close',
 'Open',
 'Bid',
 'Ask',
 'Days_Range',
 '52_Week_Range',
 'Volume',
 'Avg_Volume',
 'Market_Cap',
 'Beta_3Y_Monthly',
 'PE Ratio_TTM',
 'EPS_TTM',
 'Earnings_Date',
 'Forward_Dividend',
 'Ex_Dividend_Date',
 'one_y_Target_Est']

In [130]:
for col in list(finished_df_2017.columns):    
    finished_df_2017.drop(finished_df_2017.loc[finished_df_2017[col]=="N/A"].index, inplace=True)

In [131]:
len(finished_df_2017)

6

In [7]:
data_2017 = pd.read_csv("final_df_2018.csv")

In [8]:
data_2017

,Stock_Ticker,Previous_Close,Open,Bid,Ask,Days_Range,52_Week_Range,Volume,Avg_Volume,Market_Cap,Beta_3Y_Monthly),PE Ratio_TTM,EPS_TTM,Earnings_Date,Forward_Dividend,Ex_Dividend_Date,one_y_Target_Est
0,MMM,203.63,202.55,"5,449,476","2,970,514",200.11 - 205.06,191.44 - 259.77,NaN,NaN,121.689,1.08,30.36,6.750,NaN,NaN,2018-05-17,213.00
1,ABT,63.27,63.28,63.330 x 1000,63.340 x 1200,62.910 - 63.481,47.170 - 64.600,2028.0,2815234.0,110.933,1.67,235.22,0.269,NaN,NaN,2018-04-12,68.56
2,ABBV,93.12,93.95,"6,812,358","8,457,054",92.54 - 94.56,69.38 - 125.86,NaN,NaN,142.231,1.67,23.62,3.980,NaN,NaN,2018-07-12,112.38
3,ATVI,75.94,76.04,"7,919,562","5,976,420",75.70 - 77.52,55.86 - 79.63,NaN,NaN,58.362,0.79,212.97,0.360,NaN,NaN,2018-03-28,75.88
4,AMD,15.25,15.21,15.5500 x 1200,15.5600 x 46000,15.010 - 15.660,9.040 - 15.970,36587.0,36804542.0,15.175,3.36,391.25,0.040,NaN,NaN,1995-04-27,14.31
5,AES,NaN,NaN,NaN,NaN,10.71 - 10.92,9.87 - 12.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,A,65.65,65.69,"2,287,703","2,490,201",65.53 - 65.99,60.42 - 75.00,NaN,NaN,21.018,1.45,71.95,0.910,NaN,NaN,2018-07-02,78.07
7,APD,NaN,NaN,NaN,NaN,162.39 - 165.01,133.63 - 175.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ALB,NaN,NaN,NaN,NaN,98.58 - 100.62,90.49 - 144.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ARE,NaN,NaN,NaN,NaN,124.75 - 126.24,106.89 - 134.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ALXN,118.33,118.12,117.40 x 800,117.49 x 900,116.44 - 118.31,102.10 - 149.34,360519.0,360992492.0,26.137,1.06,59.63,1.970,NaN,NaN,NaN,158.79
11,ALGN,NaN,NaN,NaN,NaN,245.00 - 272.00,191.80 - 287.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LNT,NaN,NaN,NaN,NaN,43.64 - 43.97,34.88 - 43.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MO,57.79,57.38,56.25 x 3200,56.75 x 800,56.13 - 57.39,53.91 - 77.79,7621.0,7552393.0,107.226,0.48,10.11,5.600,NaN,NaN,2018-06-14,69.31
14,AMZN,NaN,NaN,"1,704.41 x 800","1,705.75 x 800","1,700.12 - 1,713.75","931.75 - 1,714.50",3091.0,3981335.0,827.244,1.70,277.21,6.150,NaN,NaN,NaN,NaN
15,AEE,NaN,NaN,NaN,NaN,53.08 - 54.00,51.89 - 64.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,AAL,43.11,43.25,44.43 x 1000,44.44 x 800,43.25 - 44.93,40.65 - 59.08,3640.0,3650014.0,20.795,1.31,11.39,3.900,NaN,NaN,2018-05-07,59.71
17,AEP,NaN,NaN,NaN,NaN,64.64 - 65.52,63.32 - 78.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,AXP,99.91,99.91,98.65 x 1000,100.24 x 1300,99.57 - 100.47,83.33 - 103.24,4675.0,4524941.0,85.959,0.94,29.03,3.440,NaN,NaN,2018-07-05,109.24
19,AMT,NaN,NaN,NaN,NaN,143.61 - 145.82,120.44 - 155.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,AWK,NaN,NaN,NaN,NaN,79.15 - 80.52,74.63 - 92.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,ABC,85.67,85.93,84.95 x 900,86.32 x 900,85.93 - 86.55,71.90 - 106.27,34317.0,34777795.0,19.024,1.23,19.58,4.420,NaN,NaN,2018-02-16,102.87
22,AME,NaN,NaN,NaN,NaN,74.29 - 76.68,52.42 - 79.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,AMGN,191.40,191.62,"1,725,123","2,977,720",190.76 - 193.46,163.31 - 201.23,NaN,NaN,127.736,1.73,63.25,3.050,NaN,NaN,2018-05-16,196.10
24,APH,NaN,NaN,NaN,NaN,88.51 - 90.48,68.57 - 93.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,ANSS,NaN,NaN,NaN,NaN,125.93 - 127.27,82.28 - 132.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,APA,NaN,NaN,NaN,NaN,34.45 - 35.45,33.60 - 54.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,AAPL,192.28,192.42,"17,996,551","29,731,529",190.46 - 192.88,142.20 - 194.20,NaN,NaN,937.317,1.11,18.44,10.340,NaN,NaN,2018-05-11,198.48
28,ARNC,21.38,21.33,21.10 x 3700,21.35 x 1600,21.13 - 21.49,16.47 - 31.17,4348.0,4756453.0,10.342,NaN,NaN,-0.660,NaN,NaN,2018-08-02,22.60
29,T,34.35,33.00,"195,082,730","29,385,331",32.21 - 33.14,31.17 - 39.80,NaN,NaN,197.863,0.39,6.50,4.960,NaN,NaN,2018-04-09,37.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,VRSN,142.27,142.15,"698,361","1,072,168",141.78 - 145.57,92.13 - 145.57,NaN,NaN,17.871,0.75,39.45,3.680,NaN,NaN,2011-05-05,118.75
292,VZ,48.81,48.45,"30,809,380","14,934,325",47.38 - 48.55,42.80 - 54.77,NaN,NaN,195.852,0.72,6.22,7.630,NaN,NaN,2018-07-09,55.68
293,VRTX,NaN,NaN,NaN,NaN,146.10 - 149.27,71.46 - 167.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,VIAB,29.09,29.00,29.09 x 1000,29.12 x 1200,28.99 - 29.22,22.13 - 35.55,368419.0,368085685.0,11.944,1.64,5.81,5.010,NaN,NaN,2018-06-14,34.50
295,V,134.86,135.18,"4,881,581","7,740,950",134.31 - 135.77,93.19 - 136.58,NaN,NaN,301.028,1.03,34.00,3.950,NaN,NaN,2018-05-17,143.76
296,VNO,67.46,67.60,58.70 x 800,"612,394",67.44 - 67.93,64.13 - 80.92,1015.0,NaN,13.733,1.12,79.85,0.850,NaN,NaN,2018-05-04,77.92
297,VMC,107.16,105.96,138.60 x 100,"1,341,380",104.48 - 107.38,82.52 - 141.20,1554.0,NaN,14.068,1.07,22.10,4.820,NaN,NaN,2018-11-20,123.54
298,WMT,84.10,83.89,84.00 x 1000,84.19 x 1400,83.85 - 84.37,73.13 - 109.98,6358.0,6803117.0,248.136,0.44,28.06,3.000,NaN,NaN,2018-08-09,95.12
299,WBA,65.80,65.45,62.00 x 1800,64.37 x 1200,63.88 - 65.54,61.56 - 83.89,3723.0,3293946.0,63.615,0.81,16.08,3.990,NaN,NaN,2018-05-17,80.96
300,WM,83.59,83.74,83.4200 x 800,83.4900 x 800,83.0700 - 83.8600,72.5000 - 89.7300,893948.0,893137893.0,36.082,0.68,18.92,4.410,NaN,NaN,2018-06-07,94.22
301,WAT,249.41,249.41,250.66 x 900,"369,763",248.68 - 252.23,167.94 - 255.21,596014.0,NaN,17.737,1.28,32.77,7.650,NaN,NaN,1996-11-26,223.92
302,WEC,NaN,NaN,NaN,NaN,67.56 - 68.20,54.24 - 68.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,WFC,54.48,54.25,"21,191,614","19,406,078",53.88 - 54.76,49.27 - 66.31,NaN,NaN,264.938,1.25,13.49,4.030,NaN,NaN,2018-05-03,60.87
304,HCN,NaN,NaN,NaN,NaN,68.00 - 68.53,60.62 - 78.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,WDC,80.89,81.26,79.68 x 800,80.15 x 800,79.54 - 81.38,75.96 - 106.96,2481.0,2902861.0,23.844,0.80,118.93,0.670,NaN,NaN,2018-06-28,116.07
306,WU,NaN,NaN,NaN,NaN,19.40 - 19.94,18.39 - 22.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,WRK,NaN,NaN,NaN,NaN,65.60 - 66.61,49.23 - 71.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,WY,34.73,34.84,"3,736,325","4,155,765",34.61 - 34.99,30.95 - 38.39,NaN,NaN,26.427,1.60,38.36,0.910,NaN,NaN,2018-06-07,38.08
309,WHR,145.31,148.98,"1,616,971","1,468,992",148.24 - 151.10,143.11 - 202.99,NaN,NaN,10.564,1.73,31.75,4.700,NaN,NaN,NaN,187.30
310,WMB,26.97,27.00,"4,630,295","9,597,951",26.74 - 27.20,20.36 - 32.22,NaN,NaN,32.794,1.51,NaN,-0.160,NaN,1.52,2019-03-07,31.94
311,WYN,110.82,110.94,"2,767,632","2,925,665",108.05 - 110.95,43.02 - 110.95,NaN,NaN,10.820,1.41,12.91,8.400,NaN,NaN,2018-03-14,119.67
312,WYNN,178.12,179.44,180.65 x 900,180.70 x 900,179.11 - 183.37,124.11 - 203.63,2904.0,2512425.0,19.693,1.93,24.91,7.280,NaN,NaN,2018-05-16,213.25
313,XEL,NaN,NaN,NaN,NaN,48.26 - 48.64,38.00 - 50.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,XRX,27.98,28.04,28.23 x 1000,28.24 x 900,27.80 - 28.29,27.11 - 37.42,1543.0,1613885.0,7.187,1.15,39.63,0.710,NaN,NaN,2018-03-28,40.20
315,XLNX,90.54,91.31,89.04 x 1100,89.06 x 800,88.79 - 91.87,62.27 - 95.18,791820.0,791126867.0,22.551,0.53,38.51,2.310,NaN,NaN,2018-11-09,87.27
316,XL,NaN,NaN,NaN,NaN,55.26 - 55.41,33.77 - 56.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,YUM,83.18,83.36,83.30 x 1000,83.32 x 900,82.79 - 83.49,70.90 - 88.07,1949.0,1261226.0,26.908,0.45,19.50,4.270,NaN,NaN,2018-05-15,88.17
318,ZBH,121.91,121.38,121.99 x 900,122.00 x 1100,118.80 - 122.36,96.99 - 134.55,983344.0,983220706.0,24.979,1.36,NaN,-1.510,NaN,0.96,2019-03-28,135.19
319,ZION,NaN,NaN,NaN,NaN,52.96 - 54.07,38.43 - 54.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,ZTS,NaN,NaN,NaN,NaN,84.33 - 85.54,52.25 - 85.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_2017_filtered_1 = data_2017.drop(['Volume'], axis=1).drop(['Avg_Volume'], axis=1).drop(['Earnings_Date'], axis=1)

In [ ]:
df_2017_filtered_1

In [169]:
df_2017_filtered_2 = df_2017_filtered_1.drop(['Bid'], axis=1).drop(['Ask'], axis=1)\
.drop(['Days_Range'], axis=1).drop(['52_Week_Range'], axis=1).drop(['Ex_Dividend_Date'], axis=1)

In [170]:
df_2017_filtered_3 = df_2017_filtered_2.dropna()

In [171]:
df_2017_filtered_3

,Stock_Ticker,Previous_Close,Open,Market_Cap,Beta_3Y_Monthly),PE Ratio_TTM,EPS_TTM,Forward_Yeild,one_y_Target_Est
0,MMM,161.89,162.51,96.349,1.28,19.99,8.31,3.52,172.00
1,ABT,81.36,81.45,144.308,0.80,44.38,1.84,1.57,94.03
2,ABBV,76.80,76.39,113.148,0.71,27.94,2.74,5.57,87.80
3,ATVI,55.44,56.21,42.386,0.94,25.23,2.19,0.67,57.79
5,AES,16.88,16.82,11.153,0.74,28.00,0.60,3.23,18.50
6,A,75.00,74.70,23.331,1.28,22.55,3.34,0.87,83.33
7,APD,211.47,211.48,46.993,0.72,27.59,7.73,2.19,240.00
8,ALB,69.45,63.79,6.740,1.25,12.41,5.12,2.12,84.37
9,ARE,159.16,159.03,18.040,0.52,45.27,3.50,2.54,157.82
12,LNT,53.66,53.62,12.631,0.22,24.63,2.16,2.65,52.44
13,MO,46.96,46.68,87.427,0.37,13.97,3.35,7.16,52.68
15,AEE,77.49,77.58,18.826,0.23,23.72,3.23,2.56,80.78
16,AAL,29.41,29.40,13.741,1.98,8.56,3.61,1.36,36.76
17,AEP,95.72,95.69,46.590,0.13,21.89,4.31,2.93,96.38
18,AXP,116.41,116.36,96.769,0.99,14.28,8.28,1.48,132.21
19,AMT,223.47,223.19,95.917,-0.01,65.46,3.31,1.62,221.60
20,AWK,122.31,122.58,21.879,0.16,37.74,3.21,1.64,123.73
21,ABC,85.98,85.91,18.083,1.18,19.31,4.49,1.86,95.13
22,AME,89.12,89.25,20.542,1.33,25.27,3.56,0.63,97.57
23,AMGN,203.06,202.59,121.769,0.79,16.12,12.60,2.86,215.62
24,APH,101.79,101.68,29.813,1.12,26.29,3.81,0.98,107.18
28,ARNC,27.43,27.43,11.979,1.93,29.82,0.93,0.29,29.89
29,T,36.82,36.94,269.701,0.77,15.57,2.37,5.54,36.50
31,ADP,162.54,162.01,70.242,0.97,30.91,5.24,1.94,179.88
32,AVY,126.20,126.34,10.676,1.46,45.53,2.79,1.84,127.22
33,BLL,71.80,71.73,23.874,0.52,47.12,1.53,0.84,76.45
34,BAC,31.36,31.36,287.994,1.64,11.69,2.71,2.30,33.30
35,BBY,72.12,71.85,19.280,1.67,13.22,5.53,2.77,76.71
37,HRB,24.87,24.90,5.054,0.49,12.16,2.07,4.18,25.00
38,BMY,54.37,54.50,89.935,0.58,14.48,3.80,3.02,60.38
...,...,...,...,...,...,...,...,...,...
277,USB,56.31,56.25,89.413,1.23,13.04,4.35,2.98,57.02
278,UDR,49.44,49.35,14.472,0.49,86.40,0.57,2.77,49.42
281,UNP,170.39,170.39,119.631,1.19,20.31,8.49,2.28,180.20
283,UNH,244.51,243.91,232.097,0.70,17.82,13.75,1.77,285.16
285,UTX,143.44,143.35,123.388,1.31,24.12,5.93,2.05,156.53
286,UHS,144.70,137.95,12.205,1.23,17.15,8.04,0.55,160.59
287,VFC,90.82,84.90,33.507,1.44,29.40,2.86,1.89,101.38
288,VLO,96.91,98.00,41.138,1.74,17.93,5.54,3.71,103.11
290,VTR,72.47,70.27,24.591,0.19,47.41,1.39,4.37,71.39
292,VZ,60.58,60.60,249.676,0.47,15.77,3.83,4.06,61.04
294,VIAB,21.49,21.48,8.843,1.05,5.34,4.05,3.72,31.73
295,V,176.16,174.93,398.455,0.81,34.15,5.21,0.57,201.09
296,VNO,64.52,64.50,12.265,0.89,4.28,15.02,4.09,70.25
297,VMC,145.40,145.50,19.457,0.85,34.71,4.24,0.85,156.19
298,WMT,119.10,119.00,338.583,0.65,26.92,4.42,1.78,121.91
299,WBA,54.45,54.20,50.052,0.83,10.85,5.11,3.36,57.14
300,WM,113.17,113.15,47.239,0.59,27.21,4.09,1.81,126.45
302,WEC,94.01,94.22,29.585,0.14,27.19,3.45,2.51,90.17
303,WFC,51.10,51.08,220.160,1.19,11.10,4.65,3.99,50.28
306,WU,24.77,24.75,10.521,0.65,9.06,2.74,3.23,21.53
307,WRK,37.60,37.58,9.782,1.63,11.81,3.22,4.84,44.38
309,WHR,160.53,160.00,10.072,1.89,9.61,16.58,2.99,158.00
310,WMB,23.22,23.20,28.167,1.43,528.18,0.04,6.55,29.32
312,WYNN,117.11,116.55,13.005,1.81,15.91,7.60,3.42,132.04
313,XEL,64.54,64.67,33.371,0.19,25.43,2.50,2.51,65.00
314,XRX,30.38,30.28,6.923,2.07,13.84,2.20,3.47,37.25
315,XLNX,93.12,93.37,23.972,1.48,25.86,3.67,1.59,108.12
317,YUM,108.95,108.83,33.198,0.40,25.96,4.20,1.54,118.82
319,ZION,47.51,47.46,8.169,1.53,11.20,4.28,2.86,50.43
320,ZTS,122.95,123.17,59.389,0.61,43.94,2.83,0.53,136.00

In [172]:
df_2017_filtered_3.to_csv('filtered_df_2019.csv',index=False)